export const jobsData = [
  {
    company: 'Stripe',
    role: 'Senior Software Engineer',
    salary: '$200K-$240K',
    url: 'https://stripe.com/jobs',
    cover_letter: 'I am excited about Stripe\'s mission to increase the economic productivity of the internet. With my experience building scalable financial systems and deep understanding of payment infrastructure, I can contribute meaningfully to Stripe\'s platform. My track record of shipping reliable, high-performance systems aligns perfectly with Stripe\'s engineering culture.',
  },
  {
    company: 'Block',
    role: 'Staff Engineer',
    salary: '$210K-$250K',
    url: 'https://block.xyz/careers',
    cover_letter: 'Block\'s ecosystem of financial services resonates with my passion for building inclusive financial infrastructure. I have extensive experience architecting distributed systems and leading cross-functional engineering initiatives. I\'m confident I can drive significant technical impact at Block.',
  },
  {
    company: 'PayPal',
    role: 'Principal Engineer',
    salary: '$180K-$220K',
    url: 'https://careers.paypal.com',
    cover_letter: 'PayPal\'s commitment to democratizing financial services aligns with my core values. With proven expertise in payments, fraud detection, and fintech systems, I can contribute to PayPal\'s mission of empowering financial freedom globally.',
  },
  {
    company: 'Toast',
    role: 'Engineering Manager',
    salary: '$170K-$210K',
    url: 'https://www.toasttab.com/careers',
    cover_letter: 'Toast\'s impact on the restaurant industry through cloud-based solutions is impressive. My experience managing high-performing engineering teams combined with deep product knowledge makes me an ideal fit for leading Toast\'s platform initiatives.',
  },
  {
    company: 'Carta',
    role: 'Backend Engineer',
    salary: '$160K-$200K',
    url: 'https://carta.com/careers',
    cover_letter: 'Carta\'s mission to unlock economic opportunity for equity holders is compelling. My background in building robust financial platforms and handling complex data transformations will enable me to contribute meaningfully to Carta\'s growing platform.',
  },
  {
    company: 'Google',
    role: 'Software Engineer',
    salary: '$190K-$230K',
    url: 'https://careers.google.com',
    cover_letter: 'Google\'s commitment to organizing the world\'s information inspires me. My expertise in distributed systems, search infrastructure, and large-scale data processing positions me well to contribute to Google\'s mission of connecting billions of users globally.',
  },
  {
    company: 'Affirm',
    role: 'Senior Backend Engineer',
    salary: '$165K-$205K',
    url: 'https://www.affirm.com/careers',
    cover_letter: 'Affirm\'s vision to empower consumers financially resonates deeply. With my experience in fintech, risk modeling, and consumer-facing platforms, I can help Affirm scale its impact on consumer financial health.',
  },
  {
    company: 'Shopify',
    role: 'Infrastructure Engineer',
    salary: '$175K-$215K',
    url: 'https://www.shopify.com/careers',
    cover_letter: 'Shopify\'s mission to make commerce better for everyone is transformational. My background in building scalable infrastructure and supporting millions of merchants globally makes me well-positioned to drive Shopify\'s technical excellence.',
  },
  {
    company: 'TPG',
    role: 'Technology Associate',
    salary: '$150K-$190K',
    url: 'https://www.tpg.com/careers',
    cover_letter: 'TPG\'s leadership in growth investment requires deep technical acumen. My experience in building enterprise systems and analyzing complex business problems will enable me to deliver exceptional value to TPG\'s portfolio companies.',
  },
  {
    company: 'Airbnb',
    role: 'Senior Software Engineer',
    salary: '$185K-$225K',
    url: 'https://careers.airbnb.com',
    cover_letter: 'Airbnb\'s mission to belong anywhere is inspiring. My track record building consumer platforms at scale, combined with expertise in distributed systems and real-time data, positions me to contribute meaningfully to Airbnb\'s global impact.',
  },
  {
    company: 'Amazon',
    role: 'Senior Software Development Engineer',
    salary: '$170K-$210K',
    url: 'https://www.amazon.jobs',
    cover_letter: 'Amazon\'s customer obsession and operational excellence drive my interest. With my proven ability to operate at scale, mentor teams, and deliver measurable business impact, I can help Amazon continue its innovation trajectory across diverse markets.',
  },
  {
    company: 'Betterment',
    role: 'Engineering Lead',
    salary: '$155K-$195K',
    url: 'https://www.betterment.com/careers',
    cover_letter: 'Betterment\'s democratization of wealth management aligns with my belief in financial inclusion. My experience building user-centric fintech products and leading engineering initiatives will help Betterment scale its impact.',
  },
  {
    company: 'Klarna',
    role: 'Backend Engineer',
    salary: '$160K-$200K',
    url: 'https://www.klarna.com/careers',
    cover_letter: 'Klarna\'s transformation of shopping and payment experiences globally is exciting. My expertise in building reliable payment systems and handling high-volume transactions positions me to contribute to Klarna\'s continued growth.',
  },
  {
    company: 'Plaid',
    role: 'Infrastructure Engineer',
    salary: '$180K-$220K',
    url: 'https://plaid.com/careers',
    cover_letter: 'Plaid\'s mission to empower fintech innovation through robust financial connectivity is compelling. With my background in building fault-tolerant systems and managing complex integrations, I can help Plaid strengthen its platform.',
  },
  {
    company: 'DoorDash',
    role: 'Senior Software Engineer',
    salary: '$175K-$215K',
    url: 'https://careers.doordash.com',
    cover_letter: 'DoorDash\'s vision to unlock economic opportunity for merchants and customers is transformational. My experience building real-time systems, managing logistics at scale, and optimizing for user experience will enable me to drive impact across DoorDash\'s platform.',
  },
];
